[theme]
primaryColor = "#FFD700"  # Luxurious gold accent
backgroundColor = "#121212"  # Dark premium background
secondaryBackgroundColor = "#1E1E1E"  # Dark contrast section
textColor = "#E0E0E0"  # Soft white text for readability
font = "serif"  # Elegant, premium feel
