[theme]
primaryColor = "#DAA520"  # Rich goldenrod
backgroundColor = "#FFF8E7"  # Soft cream (warm, luxurious feel)
secondaryBackgroundColor = "#FAF3DD"  # Lighter cream for contrast
textColor = "#4B3621"  # Deep brown (classy & readable)
font = "serif"  # Elegant, premium feel
